export enum PaymentMethodEnum {
  CREDIT_CARD = 'CREDIT_CARD',
  DANA = 'DANA',
  DEBIT_CARD = 'DEBIT_CARD',
  GOPAY = 'GOPAY',
  OVO = 'OVO',
  QRIS = 'QRIS',
  SHOPEE_PAY = 'SHOPEE_PAY',
  VIRTUAL_ACCOUNT_BCA = 'VIRTUAL_ACCOUNT_BCA',
  VIRTUAL_ACCOUNT_BNI = 'VIRTUAL_ACCOUNT_BNI',
  VIRTUAL_ACCOUNT_BRI = 'VIRTUAL_ACCOUNT_BRI',
  VIRTUAL_ACCOUNT_MANDIRI = 'VIRTUAL_ACCOUNT_MANDIRI',
  VIRTUAL_ACCOUNT_PERMATA = 'VIRTUAL_ACCOUNT_PERMATA',
}
